name: Release to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

permissions:
  contents: read
  packages: write
  id-token: write

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  pack-and-push:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install .NET MAUI Workload
        run: dotnet workload restore src\Plugin.Maui.Rive.sln

      - name: Download native dependencies
        shell: bash
        run: ./download-native-deps.sh

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Get version
        id: get_version
        run: |
          $version = if ("${{ inputs.version }}" -ne "") { "${{ inputs.version }}" } else { "${{ github.ref_name }}".TrimStart("v") }
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Pack
        run: dotnet pack src\Plugin.Maui.Rive.sln -c Release -p:PackageVersion=${{ steps.get_version.outputs.version }} -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts/*.*nupkg

      - name: NuGet login (OIDC)
        uses: nuget/login@v1
        id: nuget-login
        with:
          user: jfversluis

      - name: Push to NuGet
        run: |
          dotnet nuget push "artifacts\*.nupkg" `
            --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" `
            --source https://api.nuget.org/v3/index.json `
            --skip-duplicate
